

/*export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}*/
import { Metadata } from "next";
export const metadata: Metadata = {
    title: {
        absolute: 'About | Ahmed Aziz Jenhani',
        
    },
    description: 'About of Ahmed Aziz Jenhani'
}
export default function AboutLayout({ children }) {
    return (
       
            <main  >{children}</main>
       
    )
}
